Typescript rewrite
Dynox-Host/dynoxhost.js pull request #4
Opened 2021-05-16 18:06 UTC by tovade

This PR includes

-DynoxHost rewritten in typescript
- typings removed because typescript makes them when building the files
- when publishing to npm dont forget to do `tsc`
more questions? let me know!

2021-05-16 19:31 UTC, devnote-dev commented
Since this is being rewritten, a few things can be fixed in this PR too :P

2021-05-16 19:32 UTC, LogischJo commented
> Since this is being rewritten, a few things can be fixed in this PR too :P

Which things do you mean?

2021-05-16 19:33 UTC, devnote-dev requested changes

2021-05-16 19:33 UTC, devnote-dev commented on src/DynoxHost.ts
> +         * @param {String} id Server ID
JSDocs are meant to be before declaration :P

2021-05-16 19:33 UTC, devnote-dev commented on src/DynoxHost.ts
> +         * @param {String} id Server ID
same here

2021-05-16 19:33 UTC, devnote-dev commented on src/DynoxHost.ts
> +         * @param {String} state Power State
and here

2021-05-16 19:33 UTC, devnote-dev commented on src/DynoxHost.ts
> +         * @param {String} id Server ID
here too

2021-05-16 19:33 UTC, devnote-dev commented on src/DynoxHost.ts
> +         * @param {String} backupID Backup ID
and also here

2021-05-16 19:33 UTC, devnote-dev commented on src/DynoxHost.ts
> +        let json = res.json();
this can be shortened to `return res.json();`

2021-05-16 20:44 UTC, tovade commented
I can remove them as typescript auto will show them

2021-05-17 18:54 UTC, tovade commented
ready to merge 👍

2021-05-17 18:58 UTC, devnote-dev approved these changes

2022-03-24 13:17 UTC, closed without merging